### ISSUE TITLE
Remove `Lorem ipsum`

### ISSUE THREAD

**Issue by andrewbahlov** [nearby-sharing/web#2]
Site: https://nearshare.shortdev.de/
Mistake: Below second step ('Step 2: Download the app on your phone') 
standard text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sagittis, quam nec venenatis lobortis, mirisus tempus nulla, sed porttitor est nibh at nulla.'
https://github.com/nearby-sharing/web/blob/c537947b08f698a968da2f10c532df7f90615ab2/src/pages/index.astro#L50-L56

**Comment by ShortDevelopment** [comment]
@UrielErck Uups, that's bad ... thanks for the report!
(I've just transfered you issue to the right repo 😉)

**Comment by andrewbahlov** [comment]
Good, thanks! I love you work, and think that you app better then google
nearby share for windows (because it faster in work)
